# Generated by Django 2.2.3 on 2019-07-29 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoapp', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='momo',
            new_name='memo',
        ),
    ]
