# Generated by Django 2.2.3 on 2019-07-29 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoapp', '0003_auto_20190729_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='memo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='memoapp.Memo'),
        ),
    ]
